semantic_regions:
  - id: 1
    tags: "living room"
    zone: [[0.5, -9.1],[0.5, -0.41],[9.6, -0.4],[9.6, -9.6]]
    passage: [[-1.6, 0.3],[7.4, 0.3]]
  - id: 2
    tags: "bedroom"
    zone: [[-9, 0.7],[-9, 8.85],[-1.05, 9.41],[-1, 0.8]]
    passage: [[-1.6, 0.3],[-0.14, 4.26]]
  - id: 3
    tags: "dinningroom"
    zone: [[0.4, 0.9],[0.5, 9.6],[9.6, 9.6],[9.6, 1]]
    passage: [[-0.14, 4.26],[7.4, 0.3]]
  - id: 4
    tags: "guestroom"
    zone: [[-9.4,-9.4],[-9.4,-0.2],[-0.6,-0.1],[-0.6,-9.2]]
    passage: [[-1.6, 0.3],[-0.1, -3.9]]
