semantic_regions:
  - id: 1
    tags: "shelf_in_guestroom"
    zone: [[-9.3, -7.4],[-9.4,-5.6],[-8.4,-5.6],[-8.4,-7.4]]
    passage: [[-7.8, -6.5]]
  - id: 2
    tags: "door_in_guestroom"
    zone: [[-9.9, -2.7],[-9.9,-0.1],[-9.3, -0.1],[-9.3, -2.7]]
    passage: [[-8.25, -1.5]]
  - id: 3
    tags: "guestroom"
    zone: [[-9.4,-9.4],[-9.4,-0.2],[-0.6,-0.1],[-0.6,-9.2]]
    passage: [[-1.6, 0.3],[-0.1, -3.9]]
  - id: 4
    tags: "desk_in_bedroom"
    zone: [[-9.1,0.6],[-9.1,2.4],[-4.7,2.4],[-4.7, 0.6]]
    passage: [[-4.6, 3.1]]
  - id: 5
    tags: "shelf_in_bedroom"
    zone: [[-9.4,5.8],[-9.4, 7.2],[-8.6, 7.2],[-8.6, 5.8]]
    passage: [[-7.9, 6.6]]
  - id: 6
    tags: "door_in_bedroom"
    zone: [[-3.2, 10.0],[-3.2, 10.4],[-0.3, 10.4],[-0.3, 10.0]]
    passage: [[-2.0, 9.0]]
  - id: 7
    tags: "bedroom"
    zone: [[-9.5, 0.5],[-9.5, 10.2],[-0.4, 10.2],[-0.4, 0.5]]
    passage: [[-4.8, 5.4]]
  - id: 8
    tags: "shelf_in_dinningroom"
    zone: [[0.15, 7.5],[0.15, 9.4],[1.0, 9.5],[1.0, 7.4]]
    passage: [[1.5, 8.4]]
  - id: 9
    tags: "table_in_dinningroom"
    zone: [[3.3, 4.2],[3.2, 8.7],[5.0, 8.7],[5.0, 4.2]]
    passage: [[2.5, 4.7]]
  - id: 10
    tags: "desk_in_dinningroom"
    zone: [[8.2, 6.1],[8.2, 9.9],[9.9, 9.9],[9.9, 6.1]]
    passage: [[7.6, 7.6]]
  - id: 11
    tags: "dishwasher_in_dinningroom"
    zone: [[8.2, 4.0],[8.2, 5.8],[9.8, 5.8],[9.8, 4.0]]
    passage: [[7.4, 4.8]]
  - id: 12
    tags: "dinningroom"
    zone: [[0.2, 0.6],[0.2, 10.1],[10.0, 10.1],[10.0, 0.6]]
    passage: [[1.4, 4.2]]
  - id: 13
    tags: "shelf_in_livingroom"
    zone: [[],[],[],[]]
    passage: [[]]
  - id: 14
    tags: "table_in_livingroom"
    zone: [[0.2, -8.4],[0.2, -5.7],[1.1, -5.7],[1.27, -8.3]]
    passage: [[2.0, -6.9]]
  - id: 15
    tags: "livingroom"
    zone: [[0.2, -9.5],[0.2, 0.1],[10.0, 0.1],[10.0, -9.5]]
    passage: [[3.7, -3.7]]
    

